/*
 * action 类型
 */
export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const RECEIVE_AUTHED_USER = 'RECEIVE_AUTHED_USER';

export const SELECT_NOTE = 'SELECT_NOTE';
export const SELECT_NOTEBOOK = 'SELECT_NOTEBOOK';
export const REQUEST_NOTEBOOKS = 'REQUEST_NOTEBOOKS';
